'use strict';
const ICONS={sun:'<circle cx="12" cy="12" r="4"/><path d="M12 2v2m0 16v2M2 12h2m16 0h2M5 5l1.5 1.5m11 11L19 19M5 19l1.5-1.5m11-11L19 5"/>',workout:'<path d="m6 7 11 11M4 6l2-2m12 16 2-2M3 10l7-7m4 18 7-7M3 5l2-2m14 18 2-2"/>',journal:'<path d="M5 3h12a2 2 0 0 1 2 2v16H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2Zm0 0v18m4-12h6m-6 4h4"/>',meditate:'<path d="M12 20c-6 0-9-3-9-8 4 0 7 2 9 8Zm0 0c6 0 9-3 9-8-4 0-7 2-9 8Zm0-16c-5 5-5 9 0 13 5-4 5-8 0-13Z"/>',book:'<path d="M12 5v16M3 3c4 0 7 0 9 2 2-2 5-2 9-2v16c-4 0-7 0-9 2-2-2-5-2-9-2Z"/>',moon:'<path d="M20.5 13A8.5 8.5 0 0 1 11 3.5 8.5 8.5 0 1 0 20.5 13Z"/>',focus:'<circle cx="12" cy="12" r="8"/><circle cx="12" cy="12" r="3"/><path d="M12 2v2m0 16v2M2 12h2m16 0h2"/>',swim:'<path d="m4 11 5-4 5 4-4 4M8 5l4-2 5 3M2 18q2-2 4 0t4 0 4 0 4 0 4 0"/><circle cx="18" cy="10" r="2"/>',drop:'<path d="M12 3C9 7 5 11 5 15a7 7 0 0 0 14 0c0-4-4-8-7-12Z"/>',check:'<path d="m5 12 4 4L19 6"/>',close:'<path d="m6 6 12 12M6 18 18 6"/>',spark:'<path d="m12 2 2.5 7.5L22 12l-7.5 2.5L12 22l-2.5-7.5L2 12l7.5-2.5Z"/>',chart:'<path d="M5 20V10m7 10V4m7 16v-7"/>',grid:'<rect x="3" y="3" width="6" height="6" rx="1"/><rect x="15" y="3" width="6" height="6" rx="1"/><rect x="3" y="15" width="6" height="6" rx="1"/><rect x="15" y="15" width="6" height="6" rx="1"/>',edit:'<path d="m15 4 5 5M3 21l5-1L21 7a2 2 0 0 0-5-5L3 15Z"/>',info:'<circle cx="12" cy="12" r="9"/><path d="M12 11v6m0-10v.1"/>',left:'<path d="m14 6-6 6 6 6"/>',right:'<path d="m10 6 6 6-6 6"/>',lock:'<rect x="5" y="10" width="14" height="11" rx="2"/><path d="M8 10V6a4 4 0 0 1 8 0v4m-4 4v3"/>',flame:'<path d="M12 2c2 6-3 7-1 11 1-3 3-3 4-5 5 5 5 13-3 13-9 0-10-10-5-13-1 4 2 5 2 3-1-4 2-6 3-9Z"/>'};
const svg=n=>`<svg viewBox="0 0 24 24" aria-hidden="true">${ICONS[n]||ICONS.focus}</svg>`;
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const keyFor=d=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;
const dateFrom=k=>new Date(k+'T12:00:00');
const offsetDay=(key,n)=>{const d=dateFrom(key);d.setDate(d.getDate()+n);return keyFor(d)};
const fmt=n=>Number.isInteger(n)?String(n):n.toFixed(1).replace(/\.0$/,'');
const STORE='nocturne.pending.v2';
const initialState=()=>({days:{},exams:[{name:'',date:'',improvements:''},{name:'',date:'',improvements:''}],reviews:{},quote:{text:'The secret of your future is hidden in your daily routine.',author:''}});
let storageOk=true,state=initialState(),baseline={},pending=[],flushing=null,loaded=false;
try{const draft=JSON.parse(localStorage.getItem(STORE));if(Array.isArray(draft))pending=draft}catch{}
let today=keyFor(new Date()),view='tasks',selected=today,month=new Date(new Date().getFullYear(),new Date().getMonth(),1),toastTimer;
const main=document.getElementById('main'),modal=document.getElementById('modal');
let activeReview=null,reviewTimer=null,autoReviewShown=new Set();
function flatten(data){const records={quote:data.quote};data.exams.forEach((exam,i)=>records['exam/'+i]=exam);for(const [date,review] of Object.entries(data.reviews))records['review/'+date]=review;for(const [k,d] of Object.entries(data.days)){records[k+'/day']=true;records[k+'/water']=d.water||0;for(const [id,e] of Object.entries(d.tasks))records[k+'/task/'+id]=e}return records}
function saveDraft(){try{localStorage.setItem(STORE,JSON.stringify(pending))}catch{}}
function syncLabel(){document.getElementById('sync-banner').hidden=storageOk&&!pending.length;document.querySelectorAll('.sync-label').forEach(el=>el.textContent=!storageOk?'Not synced · tap to retry':pending.length?'Saving your progress…':'Saved privately · available on your devices')}
async function flush(){if(flushing)return flushing;if(!pending.length)return;flushing=(async()=>{while(pending.length){const batch=pending.slice(0,1);try{const r=await fetch('/api/state',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({changes:batch})});if(!r.ok)throw new Error('save failed');pending.splice(0,batch.length);saveDraft();storageOk=true;syncLabel()}catch{storageOk=false;syncLabel();toast('Not synced yet. Tap the save status to retry.');break}}})().finally(()=>{flushing=null;syncLabel()});syncLabel();return flushing}
function save(){if(!loaded)return Promise.resolve();const current=flatten(state);for(const key of new Set([...Object.keys(current),...Object.keys(baseline)])){if(JSON.stringify(current[key])!==JSON.stringify(baseline[key]))pending.push({key,value:current[key]??null})}baseline=JSON.parse(JSON.stringify(current));saveDraft();syncLabel();return flush()}
async function loadState(){main.innerHTML='<div class="empty-state"><strong>Welcome to your practice.</strong>Opening your private journal…</div>';try{if(pending.length){await flush();if(pending.length)throw new Error('pending save')}const r=await fetch('/api/state');if(!r.ok)throw new Error('load failed');const data=await r.json();state=initialState();for(const record of data.records){if(record.key==='quote'){state.quote=record.value;if(state.quote.author==='A thought to carry with you')state.quote.author='';continue}if(record.key.startsWith('exam/')){state.exams[Number(record.key.slice(5))]=record.value;continue}if(record.key.startsWith('review/')){state.reviews[record.key.slice(7)]=record.value;continue}const [k,type,id]=record.key.split('/');const d=ensureDay(k);if(type==='water')d.water=record.value;else if(type==='task')d.tasks[id]=record.value}baseline=flatten(state);loaded=true;ensureDay(today);save();render();maybeDailyReview()}catch{main.innerHTML='<div class="empty-state"><strong>Your journal is taking a moment.</strong>We couldn’t connect to your saved progress. Please try again.<br><button class="primary-button" id="retry-load" style="max-width:240px;margin-top:22px">Try again</button></div>';document.getElementById('retry-load').onclick=loadState}}
function ensureDay(k){if(!state.days[k])state.days[k]={tasks:{},water:0};return state.days[k]}
function schedule(k){const day=dateFrom(k).getDay(),weekend=day===0||day===6,friday=day===5;
 const task=(id,name,time,max,penalty,icon,phase,type='simple',detail='')=>({id,name,time,max,penalty,icon,phase,type,detail});
 const tasks=[task('wake','Rise & begin','06:20',70,17.5,'sun','Morning rituals'),task('workout','Move your body','10 MIN',50,12.5,'workout','Morning rituals'),task('journal','A page for yourself','5 MIN',30,7.5,'journal','Morning rituals'),task('meditate','Find your stillness','15 MIN',100,25,'meditate','Morning rituals')];
 if(weekend)tasks.push(task('weekend1','Morning deep work','08:00–11:00',400,100,'focus','The work','focus'),task('weekend2','Midday deep work','11:30–14:00',400,100,'focus','The work','focus'));
 else tasks.push(task('class','Classroom focus','08:00–14:00',100,0,'book','The work','class','Physics · Mathematics · Chemistry'));
 tasks.push(task('afternoon','Afternoon reset','15:20',100,25,'sun','The work'),task('session1','Focus session 01',friday?'15:30–17:30':'15:30–18:00',200,50,'focus','The work','focus'));
 if(friday)tasks.push(task('swimming','Swimming','17:30–19:00',0,0,'swim','The work','simple'));
 tasks.push(task('session2','Focus session 02',friday?'19:00–21:30':'18:30–21:30',200,50,'focus','Evening practice','focus'),task('session3','Focus session 03','22:00–00:00',400,100,'moon','Evening practice','focus'));
 return tasks.map(t=>({...t,icon:t.id}));
}
function entry(k,t){return state.days[k]?.tasks?.[t.id]||null}
function taskXP(t,e,closed=false){if(e?.status==='done')return t.max*((e.rating??100)/100);if(e?.status==='missed'||closed)return -t.penalty;return 0}
function summary(k){const record=state.days[k],tasks=schedule(k),closed=k<today;if(!record)return{xp:0,done:0,total:tasks.length,productivity:null,max:tasks.reduce((n,t)=>n+t.max,100),water:0};
 const water=record.water||0;const scores=tasks.filter(t=>t.max>0).map(t=>{const e=entry(k,t);return e?.status==='done'?(e.rating??100):0});scores.push(water/4*100);
 return{xp:tasks.reduce((n,t)=>n+taskXP(t,entry(k,t),closed),water*25-(closed?(4-water)*5:0)),done:tasks.filter(t=>entry(k,t)?.status==='done').length,total:tasks.length,productivity:Math.round(scores.reduce((a,b)=>a+b,0)/scores.length),max:tasks.reduce((n,t)=>n+t.max,100),water};
}
function streaks(){const active=Object.keys(state.days).filter(k=>summary(k).done>0).sort();let best=0,run=0,prev=null;for(const k of active){run=prev&&offsetDay(prev,1)===k?run+1:1;best=Math.max(best,run);prev=k}let cur=0,k=summary(today).done?today:offsetDay(today,-1);while(state.days[k]&&summary(k).done){cur++;k=offsetDay(k,-1)}return{current:cur,best,active:active.length}}
function toast(s){const t=document.getElementById('toast');t.textContent=s;t.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>t.classList.remove('show'),2500)}
function statsHtml(st,history=false){const yesterday=summary(offsetDay(today,-1));const run=streaks();return `<div class="stats"><div class="stat"><div class="stat-title">${svg('spark')}${history?'Total XP earned':'XP gained'}</div><div class="stat-number">${fmt(st.xp)}<small>XP</small></div><div class="progress-track"><div class="progress-fill" style="width:${Math.max(0,Math.min(100,st.done/st.total*100))}%"></div></div><div class="stat-foot">${history?'All recorded days':`${st.done} / ${st.total} complete`}</div></div><div class="stat"><div class="stat-title">${svg('chart')}${history?'Your best streak':'Yesterday'}</div><div class="stat-number">${history?run.best:(yesterday.productivity??'—')}<small>${history?'days':(yesterday.productivity===null?'':'%')}</small></div><div class="stat-foot">${history?'Personal best':yesterday.productivity===null?'No record yet':'Productivity'}</div></div><div class="stat"><div class="stat-title">${svg('flame')}Streak</div><div class="stat-number">${run.current}<small>${run.current===1?'day':'days'}</small></div><div class="stat-foot">${run.current?'Days in a row':'Start today'}</div></div></div>`}
function taskList(k,editable=true){let phase='';return schedule(k).map(t=>{const e=entry(k,t),done=e?.status==='done',missed=e?.status==='missed'||(!e&&k<today&&!!state.days[k]),earned=taskXP(t,e,k<today&&!!state.days[k]);let heading='';if(phase!==t.phase){phase=t.phase;heading=`<div class="phase-heading">${phase}</div>`}return `${heading}<article class="task-card ${done?'completed':''} ${missed?'missed':''}"><div class="task-symbol"><div class="glyph">${svg(t.icon)}</div><div class="task-time">${t.time}</div></div><div><div class="task-name">${t.name}${t.type==='focus'?'<span class="pill">Focus</span>':''}</div><div class="task-xp">${t.max?`<span class="reward">+${t.max} XP</span><span class="sep">/</span><span>−${fmt(t.penalty)} XP</span>`:'<span>Time to recharge</span>'}</div>${t.detail?`<div class="task-xp">${t.detail}</div>`:''}</div><div class="task-action"><button class="check-button" data-task="${t.id}" data-day="${k}" aria-label="${done?'Review':missed?'Update':'Check in'} ${t.name}" aria-pressed="${done}" ${!editable?'disabled':''}>${svg(missed?'close':'check')}</button>${done||missed?`<span class="earned">${earned>0?'+':''}${fmt(earned)} XP</span>`:''}</div></article>`}).join('')}
function quoteHtml(){return `<section class="quote"><div class="quote-top"><span class="eyebrow">Words to live by</span><button class="icon-button" id="edit-quote" aria-label="Edit your quote">${svg('edit')}</button></div><div class="quote-mark">“</div><blockquote>${esc(state.quote.text)}</blockquote>${state.quote.author?`<cite>${esc(state.quote.author)}</cite>`:''}</section>`}
function waterHtml(k){const water=state.days[k]?.water||0;return `<section class="water-panel"><div class="water-head"><span class="eyebrow">A moment to replenish</span>${svg('drop')}</div><div class="water-total">${water}<small> / 4 litres</small></div><div class="water-drops">${[1,2,3,4].map(n=>`<button class="${water>=n?'filled':''}" data-water="${n}" data-day="${k}" aria-label="${n} ${n===1?'litre':'litres'} of water" aria-pressed="${water>=n}">${svg('drop')}</button>`).join('')}</div><div class="water-caption">${water===4?'Daily goal reached. Nicely done.':'One glass closer to feeling better.'}</div><div class="water-meta">+25 XP / litre <span style="margin:0 5px">·</span> −5 XP / litre missed</div></section>`}
function render(){if(!loaded)return;document.getElementById('tasks-tab').innerHTML=svg('grid')+'<span>Rituals</span>';document.getElementById('streak-tab').innerHTML=svg('chart')+'<span>Streaks</span>';document.getElementById('tasks-tab').classList.toggle('active',view==='tasks');document.getElementById('streak-tab').classList.toggle('active',view==='streak');document.getElementById('tasks-tab').setAttribute('aria-current',view==='tasks'?'page':'false');document.getElementById('streak-tab').setAttribute('aria-current',view==='streak'?'page':'false');
 if(view==='streak')renderStreak();else{const d=dateFrom(today),day=d.toLocaleDateString('en-GB',{weekday:'long'}),date=d.toLocaleDateString('en-GB',{day:'2-digit',month:'2-digit'}).replace('/',' / '),st=summary(today),yesterday=offsetDay(today,-1),review=state.reviews[yesterday];
 main.innerHTML=`<div class="page-heading"><div><div class="eyebrow">${day} <span class="date-separator">/</span> ${date}</div><h1>Make today count.</h1></div></div>${statsHtml(st)}${examsHtml()}${quoteHtml()}<div class="review-entry"><button data-review="${yesterday}"><span class="review-icon">${svg('review')}</span><span><strong>Yesterday’s mistakes</strong><small>${review?.completed?'Review saved · revisit':'Reflect, check in, improve'}</small></span>${svg('right')}</button><button class="today-notes" data-review="${today}" aria-label="Today’s mistake notes">Today ${svg('edit')}</button></div><section class="task-column"><div class="section-head"><h2>Your rituals</h2><span class="subtle">${st.done} / ${st.total}</span></div>${taskList(today)}</section>${waterHtml(today)}`}
 bindContent();syncLabel();}
function renderStreak(){const monthKey=keyFor(month).slice(0,7),title=month.toLocaleDateString('en-GB',{month:'long',year:'numeric'}),first=(month.getDay()+6)%7,days=new Date(month.getFullYear(),month.getMonth()+1,0).getDate();const run=streaks(),all=Object.keys(state.days).map(summary),totalXP=all.reduce((n,s)=>n+s.xp,0);const stats={xp:totalXP,done:all.reduce((n,s)=>n+s.done,0),total:Math.max(1,all.reduce((n,s)=>n+s.total,0))};const records=Object.keys(state.days).filter(k=>k.startsWith(monthKey));const active=records.filter(k=>summary(k).done>0).length;const monthAvg=records.length?Math.round(records.reduce((n,k)=>n+(summary(k).productivity||0),0)/records.length):0;
 let cells=['Mon','Tue','Wed','Thu','Fri','Sat','Sun'].map(d=>`<div class="weekday">${d}</div>`).join('')+'<span></span>'.repeat(first);
 for(let n=1;n<=days;n++){const k=monthKey+'-'+String(n).padStart(2,'0'),s=summary(k),p=s.productivity||0,level=p>0?Math.max(1,Math.ceil(p/25)):0;cells+=`<button class="day-cell level-${level} ${k===today?'today':''} ${k===selected?'selected':''} ${k>today?'future':''}" data-calendar="${k}" aria-label="${dateFrom(k).toLocaleDateString('en-GB',{day:'numeric',month:'long'})}, ${state.days[k]?`${p}% productivity, ${s.done} rituals complete`:'no record'}" title="${n} ${title} · ${p}%" aria-pressed="${k===selected}" ${k>today?'disabled':''}></button>`}
 main.innerHTML=`<div class="page-heading"><div><div class="eyebrow">Small actions. Lasting change.</div><h1>Your consistency.</h1></div></div>${statsHtml(stats,true)}<div class="content-grid streak-layout"><section class="task-column"><div class="month-card"><div class="month-heading"><h2>${title}</h2><div class="month-controls"><button class="icon-button" id="prev-month" aria-label="Previous month">${svg('left')}</button><button class="icon-button" id="next-month" aria-label="Next month" ${monthKey>=today.slice(0,7)?'disabled':''}>${svg('right')}</button></div></div><div class="calendar">${cells}</div><div class="legend"><span>Select a day to revisit it</span><span class="legend-scale">Less ${[0,1,2,3,4].map(n=>`<i class="legend-square level-${n}"></i>`).join('')} More</span></div></div><section class="history-area"><div class="section-head"><h2>${selected===today?'Today':dateFrom(selected).toLocaleDateString('en-GB',{day:'numeric',month:'long'})}</h2><span class="subtle">${state.days[selected]?`${fmt(summary(selected).xp)} XP · ${summary(selected).productivity}%`:'No recorded activity'}</span></div><button class="history-review" data-review="${selected}">${svg('review')} Mistakes & solutions ${svg('right')}</button>${state.days[selected]?taskList(selected)+waterHtml(selected):'<div class="empty-state"><strong>A blank page.</strong>No activity was recorded on this day.<br>Your story starts with your first check-in.</div>'}</section></section><aside class="streak-aside"><div class="small-metric"><div class="eyebrow">Days you showed up</div><strong>${active}<span style="color:#66766b;font-size:25px"> / ${days}</span></strong><p>This month</p></div><div class="small-metric"><div class="eyebrow">Monthly productivity</div><strong>${monthAvg}<span style="color:#66766b;font-size:25px">%</span></strong><p>Average of ${records.length} recorded ${records.length===1?'day':'days'}</p></div><p class="streak-note">Consistency leaves a trace.<br>Each square holds a day of your practice. Come back to see how far you’ve come.</p><div class="note">${svg('info')}<span>A streak counts consecutive days with at least one completed ritual.</span></div></aside></div>`;
}
function bindContent(){document.querySelectorAll('[data-exam]').forEach(b=>b.onclick=()=>editExam(Number(b.dataset.exam)));document.querySelectorAll('[data-review]').forEach(b=>b.onclick=()=>openReview(b.dataset.review));document.querySelectorAll('[data-task]').forEach(b=>b.onclick=()=>openTask(b.dataset.day,b.dataset.task));document.querySelectorAll('[data-water]').forEach(b=>b.onclick=()=>{const d=ensureDay(b.dataset.day),n=Number(b.dataset.water);d.water=d.water===n?n-1:n;save();render();toast(`${d.water} / 4 litres recorded`)});document.getElementById('edit-quote')?.addEventListener('click',editQuote);document.querySelectorAll('[data-calendar]').forEach(b=>b.onclick=()=>{selected=b.dataset.calendar;render()});document.getElementById('prev-month')?.addEventListener('click',()=>{month=new Date(month.getFullYear(),month.getMonth()-1,1);selected=keyFor(month);render()});document.getElementById('next-month')?.addEventListener('click',()=>{month=new Date(month.getFullYear(),month.getMonth()+1,1);selected=keyFor(month).slice(0,7)===today.slice(0,7)?today:keyFor(month);render()})}
function showModal(content){persistReviewDraft();activeReview=null;modal.classList.remove('review-dialog');document.getElementById('modal-content').innerHTML=content;modal.showModal();modal.querySelector('[data-close]')?.addEventListener('click',()=>modal.close())}
function modalHeader(eyebrow,title){return `<div class="modal-heading"><div><div class="eyebrow">${eyebrow}</div><h2 id="dialog-title">${title}</h2></div><button class="icon-button" data-close aria-label="Close dialog">${svg('close')}</button></div>`}
function openTask(k,id){const t=schedule(k).find(x=>x.id===id),e=entry(k,t),done=e?.status==='done';if(t.type==='simple'&&!e&&k===today){ensureDay(k).tasks[id]={status:'done',rating:100};save();render();toast(t.max?`+${t.max} XP · A promise kept`:'Swimming complete');return}
 if(t.type==='focus'){const initial=e?.rating??75;showModal(`${modalHeader('A moment of reflection',t.name)}<p class="modal-description">How focused were you during this session?<br>An honest check-in is a step forward.</p><div class="productivity-value"><span id="rating-number">${initial}</span><small>%</small></div><div class="xp-preview" id="xp-preview">+${fmt(t.max*initial/100)} of ${t.max} XP</div><input type="range" id="rating" aria-label="Session productivity" min="0" max="100" step="1" value="${initial}"><div class="range-labels"><span>A distracted day</span><span>Fully present</span></div><button class="primary-button" id="confirm-task">${done?'Update check-in':'Save my check-in'}</button><button class="secondary-button" id="miss-task">Mark missed · −${t.penalty} XP</button>${e?'<button class="secondary-button" id="undo-task">Clear check-in</button>':''}`);
 const r=document.getElementById('rating');r.oninput=()=>{document.getElementById('rating-number').textContent=r.value;document.getElementById('xp-preview').textContent=`+${fmt(t.max*r.value/100)} of ${t.max} XP`};document.getElementById('confirm-task').onclick=()=>recordTask(k,t,{status:'done',rating:Number(r.value)});
 }else if(t.type==='class'){const values=e?.subjects||[75,75,75];showModal(`${modalHeader('Classroom reflection','Make learning count.')}<p class="modal-description">Rate your focus in each subject. Physics and mathematics carry 33 XP each; chemistry carries 34 XP.</p>${['Physics','Mathematics','Chemistry'].map((name,i)=>`<div class="class-row"><div class="class-label"><label for="subject-${i}">${name}</label><span id="subject-value-${i}">${values[i]}%</span></div><input id="subject-${i}" class="subject-range" type="range" min="0" max="100" value="${values[i]}" aria-label="${name} productivity"></div>`).join('')}<div class="xp-preview" id="class-xp"></div><button class="primary-button" id="confirm-task">Save my check-in</button><button class="secondary-button" id="miss-task">Mark missed · 0 XP</button>${e?'<button class="secondary-button" id="undo-task">Clear check-in</button>':''}`);const ranges=[...document.querySelectorAll('.subject-range')];const update=()=>{ranges.forEach((r,i)=>document.getElementById('subject-value-'+i).textContent=r.value+'%');document.getElementById('class-xp').textContent='+'+fmt(ranges.reduce((sum,r,i)=>sum+Number(r.value)*[.33,.33,.34][i],0))+' of 100 XP'};ranges.forEach(r=>r.oninput=update);update();document.getElementById('confirm-task').onclick=()=>{const subjects=ranges.map(r=>Number(r.value));recordTask(k,t,{status:'done',subjects,rating:subjects.reduce((s,v,i)=>s+v*[.33,.33,.34][i],0)})};
 }else{showModal(`${modalHeader('Endurance',t.name)}<p class="modal-description">${done?'You showed up for this ritual. You can adjust your check-in below.':'Record this ritual or mark it as missed.'}</p><button class="primary-button" id="confirm-task">${done?'Keep completed':'Mark complete'}${t.max?' · +'+t.max+' XP':''}</button><button class="secondary-button" id="miss-task">Mark missed · −${fmt(t.penalty)} XP</button>${e?'<button class="secondary-button" id="undo-task">Clear check-in</button>':''}`);document.getElementById('confirm-task').onclick=()=>recordTask(k,t,{status:'done',rating:100})}
 document.getElementById('miss-task').onclick=()=>recordTask(k,t,{status:'missed',rating:0});document.getElementById('undo-task')?.addEventListener('click',()=>{delete ensureDay(k).tasks[id];save();modal.close();render();toast('Check-in cleared')});}
function recordTask(k,t,data){ensureDay(k).tasks[t.id]=data;save();modal.close();render();const xp=taskXP(t,data);toast(`${xp>0?'+':''}${fmt(xp)} XP · Check-in saved`)}
function editQuote(){showModal(`${modalHeader('Words to return to','Your daily reminder.')}<form id="quote-form"><label class="form-label" for="quote-text">Your quote</label><textarea id="quote-text" maxlength="240" required>${esc(state.quote.text)}</textarea><label class="form-label" for="quote-author">Author or a personal note</label><input type="text" id="quote-author" maxlength="70" value="${esc(state.quote.author)}"><button class="primary-button" style="margin-top:24px" type="submit">Keep these words</button></form>`);document.getElementById('quote-form').onsubmit=ev=>{ev.preventDefault();const text=document.getElementById('quote-text').value.trim();if(!text)return;state.quote={text,author:document.getElementById('quote-author').value.trim()};save();modal.close();render();toast('Your reminder is saved')}}
function showRules(){showModal(`${modalHeader('The details','Your rhythm, explained.')}<ul class="rule-list"><li><strong>Focus XP:</strong> productivity ÷ 100 × the session reward. A 75% session worth 200 XP earns 150 XP.</li><li><strong>Daily productivity:</strong> the average of each XP-bearing ritual’s completion percentage plus hydration. Incomplete rituals count as 0%; class focus uses 33/33/34 subject weights.</li><li><strong>Missed rituals:</strong> unfinished rituals on recorded past days receive their listed penalty. Today’s pending rituals are not penalised yet. Unrecorded days never create XP debt.</li><li><strong>Your schedule:</strong> the second wake-up is treated as 15:20. Evening sessions finish at midnight. Times follow your device’s local time.</li><li><strong>Weekends:</strong> classes become two 400 XP sessions, 08:00–11:00 and 11:30–14:00.</li><li><strong>Fridays:</strong> swimming takes 17:30–19:00. The adjacent focus sessions shorten to fit. Swimming has no XP reward or penalty.</li><li><strong>Water:</strong> your requested target is 4 litres. Tap a droplet to set the total; tap the selected total again to subtract a litre.</li><li><strong>Your data:</strong> saved to your private online journal and available on your devices. If a save cannot connect, your pending changes stay on this browser until you retry.</li></ul><button class="primary-button" data-close-bottom>Back to my practice</button>`);modal.querySelector('[data-close-bottom]').onclick=()=>modal.close()}

Object.assign(ICONS,{
 wake:'<path d="M3 17h18M5 21h14M7 17a5 5 0 0 1 10 0M12 3v4M4 8l3 3m13-3-3 3"/>',
 workout:'<path d="M3 8v8m4-11v14m0-7h10m0-7v14m4-11v8"/>',
 journal:'<path d="m5 16 11-11 3 3L8 19l-4 1 1-4Zm9-9 3 3M12 21h8"/>',
 meditate:'<circle cx="12" cy="12" r="2"/><path d="M7 7a7 7 0 0 0 0 10m10-10a7 7 0 0 1 0 10M4 4a11 11 0 0 0 0 16M20 4a11 11 0 0 1 0 16"/>',
 weekend1:'<path d="m4 16 8-12 8 12H4Zm4 4h8M12 4v12"/>',
 weekend2:'<rect x="4" y="4" width="16" height="16" rx="4"/><path d="M8 16V9m4 7V7m4 9v-4"/>',
 class:'<path d="m2 9 10-5 10 5-10 5L2 9Zm4 2v6c4 3 8 3 12 0v-6m4-2v8"/>',
 afternoon:'<circle cx="12" cy="13" r="7"/><path d="M12 9v5h4M4 3 1 6m19-3 3 3M7 20l-1 2m11-2 1 2"/>',
 session1:'<path d="m14 2-10 12h7l-1 8 10-12h-7l1-8Z"/>',
 session2:'<path d="M6 3h12M6 21h12M7 3v4l10 10v4M17 3v4 0L7 17v4M7 7l10 10M9 18h6"/>',
 session3:'<path d="M4 5h16v12H4zM8 21h8m-4-4v4M7 9h2m2 0h6M7 13h10"/>',
 swimming:'<path d="M3 18q3-3 6 0t6 0 6 0M3 22q3-3 6 0t6 0 6 0M5 13l6-6 5 6M8 5l4-2 5 3"/><circle cx="19" cy="10" r="2"/>',
 review:'<rect x="5" y="4" width="14" height="17" rx="2"/><path d="M9 2h6v4H9zM9 11h6m-6 4h3"/>',
 exam:'<rect x="3" y="5" width="18" height="16" rx="3"/><path d="M7 3v4m10-4v4M3 11h18m-13 5h3"/>',
 plus:'<path d="M12 5v14M5 12h14"/>'
});
function examsHtml(){return `<section class="exam-section" aria-label="Upcoming exams"><div class="mini-section-heading">On the horizon<span>Tap to edit</span></div><div class="exam-grid">${state.exams.map((exam,i)=>{const days=exam.date?Math.round((Date.parse(exam.date)-Date.parse(today))/86400000):null;return `<button class="exam-card ${exam.date?'is-set':''}" data-exam="${i}"><span class="exam-top">${svg('exam')}<span>EXAM ${String(i+1).padStart(2,'0')}</span>${svg('edit')}</span><strong>${esc(exam.name||'Add exam name')}</strong><span class="exam-date">${exam.date?dateFrom(exam.date).toLocaleDateString('en-GB',{day:'numeric',month:'short',year:'numeric'}):'Choose a date'}</span><span class="exam-countdown">${days===null?'<b>—</b><span>days remaining</span>':days===0?'<b>Today</b>':days>0?`<b>${days}</b><span>${days===1?'day':'days'} remaining</span>`:`<b>${Math.abs(days)}</b><span>${days===-1?'day':'days'} ago</span>`}</span></button>`}).join('')}</div></section>`}
function editExam(index){const exam=state.exams[index];showModal(`${modalHeader('Exam '+String(index+1).padStart(2,'0'),'Your next milestone.')}<form id="exam-form"><label class="form-label" for="exam-name">Exam name</label><input id="exam-name" type="text" maxlength="60" value="${esc(exam.name)}" placeholder="e.g. Physics mock test"><label class="form-label" for="exam-date">Exam date</label><input id="exam-date" type="date" value="${esc(exam.date)}"><label class="form-label" for="exam-improvements">What I want to improve</label><textarea id="exam-improvements" maxlength="3000" placeholder="Topics to revisit, mistakes to avoid, and how I want to approach this exam…">${esc(exam.improvements)}</textarea><p class="field-note">Keep these notes here. Revisit them before you sit the exam.</p><button class="primary-button" type="submit">Save exam</button></form>`);document.getElementById('exam-form').onsubmit=async e=>{e.preventDefault();const name=document.getElementById('exam-name').value.trim(),date=document.getElementById('exam-date').value;const input=document.getElementById(name?'exam-date':'exam-name');input.setCustomValidity(Boolean(name)!==Boolean(date)?'Add both an exam name and a date, or leave both blank.':'');if(!document.getElementById('exam-form').reportValidity())return;state.exams[index]={name,date,improvements:document.getElementById('exam-improvements').value.trim()};save();modal.close();render();toast('Exam updated')};document.querySelectorAll('#exam-form input').forEach(input=>input.oninput=()=>document.querySelectorAll('#exam-form input').forEach(el=>el.setCustomValidity('')))}
function reviewRecord(k){return state.reviews[k]||{items:[],checks:{},completed:false}}
function mistakeRow(item){return `<div class="mistake-editor" data-mistake-id="${esc(item.id)}"><div class="mistake-row-top"><span class="eyebrow">New mistake</span><button type="button" class="icon-button remove-mistake" aria-label="Remove this mistake">${svg('close')}</button></div><label class="form-label" for="mistake-${item.id}">What went wrong?</label><textarea id="mistake-${item.id}" class="mistake-input" maxlength="500" rows="2" placeholder="Write the mistake here…">${esc(item.mistake)}</textarea><label class="form-label" for="solution-${item.id}">My solution</label><textarea id="solution-${item.id}" class="solution-input" maxlength="1000" rows="3" placeholder="What will I do differently?">${esc(item.solution)}</textarea></div>`}
function persistReviewDraft(){clearTimeout(reviewTimer);if(!activeReview)return;const items=[...modal.querySelectorAll('.mistake-editor')].map(row=>({id:row.dataset.mistakeId,mistake:row.querySelector('.mistake-input').value,solution:row.querySelector('.solution-input').value})).filter(item=>item.mistake.trim()||item.solution.trim());const checks={};modal.querySelectorAll('[data-review-check]').forEach(el=>checks[el.dataset.reviewCheck]=el.checked);state.reviews[activeReview]={items,checks,completed:reviewRecord(activeReview).completed};save()}
function bindReviewRows(){modal.querySelectorAll('.mistake-editor textarea').forEach(input=>input.oninput=()=>{clearTimeout(reviewTimer);reviewTimer=setTimeout(persistReviewDraft,400)});modal.querySelectorAll('.remove-mistake').forEach(button=>button.onclick=()=>{button.closest('.mistake-editor').remove();persistReviewDraft();document.getElementById('add-mistake').disabled=modal.querySelectorAll('.mistake-editor').length>=20})}
function openReview(k){const record=reviewRecord(k),prior=reviewRecord(offsetDay(k,-1)).items.filter(item=>item.mistake.trim());showModal(`${modalHeader(k===today?'Today’s notes':dateFrom(k).toLocaleDateString('en-GB',{day:'numeric',month:'long'}),'A little better tomorrow.')}<p class="modal-description">Check in on the previous day’s mistakes, then write what you learned from this day.</p><section class="review-checklist"><div class="mini-section-heading">Previous day’s mistakes</div>${prior.length?prior.map(item=>`<label class="mistake-check"><input type="checkbox" data-review-check="${esc(item.id)}" ${record.checks[item.id]?'checked':''}><span><strong>${esc(item.mistake)}</strong>${item.solution?`<span class="previous-solution">${esc(item.solution)}</span>`:''}<small>I avoided this mistake</small></span></label>`).join(''):'<p class="field-note">No mistakes recorded for the previous day. Start with a new note below.</p>'}</section><div id="mistake-rows">${record.items.map(mistakeRow).join('')}</div><button class="add-mistake" id="add-mistake" ${record.items.length>=20?'disabled':''}>${svg('plus')} Add a mistake</button><div class="review-actions"><button class="primary-button" id="finish-review">${k===today?'Save today’s notes':'Finish review'}</button><button class="secondary-button" id="review-later">${k===today?'Close':'Come back later'}</button><p class="field-note">Drafts save automatically. The daily review opens at midnight, or when you return.</p></div>`);activeReview=k;autoReviewShown.add(k);modal.classList.add('review-dialog');bindReviewRows();modal.querySelectorAll('[data-review-check]').forEach(input=>input.onchange=persistReviewDraft);document.getElementById('add-mistake').onclick=()=>{if(modal.querySelectorAll('.mistake-editor').length>=20)return;const item={id:crypto.randomUUID(),mistake:'',solution:''};document.getElementById('mistake-rows').insertAdjacentHTML('beforeend',mistakeRow(item));bindReviewRows();document.getElementById('add-mistake').disabled=modal.querySelectorAll('.mistake-editor').length>=20;document.getElementById('mistake-'+item.id).focus()};document.getElementById('finish-review').onclick=()=>{persistReviewDraft();state.reviews[k].completed=k<today;save();activeReview=null;modal.close();render();toast(k===today?'Notes saved':'Review complete')};document.getElementById('review-later').onclick=()=>modal.close()}
function maybeDailyReview(){if(!loaded||modal.open||document.hidden)return;const k=offsetDay(today,-1);if(!reviewRecord(k).completed&&!autoReviewShown.has(k))openReview(k)}
modal.addEventListener('close',()=>{persistReviewDraft();activeReview=null;render()});

document.getElementById('rules-button').innerHTML=svg('info');document.getElementById('rules-button').onclick=showRules;
document.getElementById('tasks-tab').onclick=()=>{view='tasks';render();window.scrollTo({top:0,behavior:'smooth'})};document.getElementById('streak-tab').onclick=()=>{view='streak';selected=today;month=new Date(dateFrom(today).getFullYear(),dateFrom(today).getMonth(),1);render();window.scrollTo({top:0,behavior:'smooth'})};document.querySelector('.brand').onclick=e=>{e.preventDefault();view='tasks';render();window.scrollTo({top:0,behavior:'smooth'})};modal.addEventListener('click',e=>{if(e.target===modal){const r=modal.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)modal.close()}});
function checkDate(){const now=keyFor(new Date());if(now!==today){today=now;selected=today;ensureDay(today);save();render();maybeDailyReview()}}
document.addEventListener('visibilitychange',()=>{if(!document.hidden&&loaded){checkDate();maybeDailyReview()}});setInterval(()=>{if(loaded){checkDate();maybeDailyReview()}},1000);window.addEventListener('online',()=>flush());window.addEventListener('beforeunload',e=>{if(pending.length){e.preventDefault();e.returnValue=''}});loadState();

const context=document.modelContext;
if(context?.registerTool){
 const controller=new AbortController();
 const tools=[{
  name:'get_daily_progress',title:'Read daily progress',description:'Read the current day’s schedule, XP, check-ins and hydration without changing any records.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:false},execute(input){if(!loaded)throw new Error('Journal is still loading');if(Object.keys(input||{}).length)throw new Error('No arguments accepted');return {date:today,...summary(today),rituals:schedule(today).map(t=>({id:t.id,name:t.name,time:t.time,maxXP:t.max,checkin:entry(today,t)}))}}},
 {name:'set_water_intake',title:'Record today’s water intake',description:'Set today’s total water intake between 0 and 4 litres, save it and update the visible tracker.',inputSchema:{type:'object',properties:{litres:{type:'integer',minimum:0,maximum:4}},required:['litres'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},async execute(input){if(!loaded)throw new Error('Journal is still loading');if(!input||Object.keys(input).length!==1||!Number.isInteger(input.litres)||input.litres<0||input.litres>4)throw new Error('Litres must be an integer from 0 to 4');ensureDay(today).water=input.litres;await save();render();if(!storageOk)throw new Error('Change recorded but waiting to sync');return {date:today,litres:input.litres,xp:summary(today).xp,saved:true}}}
 ];for(const tool of tools){try{Promise.resolve(context.registerTool(tool,{signal:controller.signal})).catch(()=>{})}catch{}}window.addEventListener('pagehide',()=>controller.abort(),{once:true});
}
