'use strict';
const ICONS={sun:'<circle cx="12" cy="12" r="4"/><path d="M12 2v2m0 16v2M2 12h2m16 0h2M5 5l1.5 1.5m11 11L19 19M5 19l1.5-1.5m11-11L19 5"/>',workout:'<path d="m6 7 11 11M4 6l2-2m12 16 2-2M3 10l7-7m4 18 7-7M3 5l2-2m14 18 2-2"/>',journal:'<path d="M5 3h12a2 2 0 0 1 2 2v16H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2Zm0 0v18m4-12h6m-6 4h4"/>',meditate:'<path d="M12 20c-6 0-9-3-9-8 4 0 7 2 9 8Zm0 0c6 0 9-3 9-8-4 0-7 2-9 8Zm0-16c-5 5-5 9 0 13 5-4 5-8 0-13Z"/>',book:'<path d="M12 5v16M3 3c4 0 7 0 9 2 2-2 5-2 9-2v16c-4 0-7 0-9 2-2-2-5-2-9-2Z"/>',moon:'<path d="M20.5 13A8.5 8.5 0 0 1 11 3.5 8.5 8.5 0 1 0 20.5 13Z"/>',focus:'<circle cx="12" cy="12" r="8"/><circle cx="12" cy="12" r="3"/><path d="M12 2v2m0 16v2M2 12h2m16 0h2"/>',swim:'<path d="m4 11 5-4 5 4-4 4M8 5l4-2 5 3M2 18q2-2 4 0t4 0 4 0 4 0 4 0"/><circle cx="18" cy="10" r="2"/>',drop:'<path d="M12 3C9 7 5 11 5 15a7 7 0 0 0 14 0c0-4-4-8-7-12Z"/>',check:'<path d="m5 12 4 4L19 6"/>',close:'<path d="m6 6 12 12M6 18 18 6"/>',spark:'<path d="m12 2 2.5 7.5L22 12l-7.5 2.5L12 22l-2.5-7.5L2 12l7.5-2.5Z"/>',chart:'<path d="M5 20V10m7 10V4m7 16v-7"/>',grid:'<rect x="3" y="3" width="6" height="6" rx="1"/><rect x="15" y="3" width="6" height="6" rx="1"/><rect x="3" y="15" width="6" height="6" rx="1"/><rect x="15" y="15" width="6" height="6" rx="1"/>',edit:'<path d="m15 4 5 5M3 21l5-1L21 7a2 2 0 0 0-5-5L3 15Z"/>',info:'<circle cx="12" cy="12" r="9"/><path d="M12 11v6m0-10v.1"/>',left:'<path d="m14 6-6 6 6 6"/>',right:'<path d="m10 6 6 6-6 6"/>',lock:'<rect x="5" y="10" width="14" height="11" rx="2"/><path d="M8 10V6a4 4 0 0 1 8 0v4m-4 4v3"/>',flame:'<path d="M12 2c2 6-3 7-1 11 1-3 3-3 4-5 5 5 5 13-3 13-9 0-10-10-5-13-1 4 2 5 2 3-1-4 2-6 3-9Z"/>'};
const svg=n=>`<svg viewBox="0 0 24 24" aria-hidden="true">${ICONS[n]||ICONS.focus}</svg>`;
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const keyFor=d=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;
const dateFrom=k=>new Date(k+'T12:00:00');
const offsetDay=(key,n)=>{const d=dateFrom(key);d.setDate(d.getDate()+n);return keyFor(d)};
const fmt=n=>Number.isInteger(n)?String(n):n.toFixed(1).replace(/\.0$/,'');
const STORE='nocturne.state.v2';
const DELETED_DAY='2026-09-20';
const initialState=()=>({days:{},dayModes:{},exams:[{name:'',date:'',improvements:''},{name:'',date:'',improvements:''}]});
let storageOk=true,state=initialState(),baseline={},pending=[],flushing=null,loaded=false;
const currentDay=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Kolkata',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
const canEdit=k=>k===currentDay();
let today=currentDay(),view='tasks',selected=today,month=new Date(new Date().getFullYear(),new Date().getMonth(),1),toastTimer;
const main=document.getElementById('main'),modal=document.getElementById('modal');
let renderedView=null;
function flatten(data){const records={};data.exams.forEach((exam,i)=>records['exam/'+i]=exam);for(const [k,d] of Object.entries(data.days)){records[k+'/day']=true;records[k+'/water']=d.water||0;for(const [id,e] of Object.entries(d.tasks))records[k+'/task/'+id]=e}return records}
function saveDraft(){}
function exportData(){if(!loaded)return;const payload={format:'nocturne-endurance',version:1,exportedAt:new Date().toISOString(),state};const blob=new Blob([JSON.stringify(payload,null,2)],{type:'application/json'});const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`endurance-backup-${today}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);toast('Backup exported')}
function importData(file){if(!file)return;const reader=new FileReader();reader.onload=()=>{try{const payload=JSON.parse(reader.result);const incoming=payload?.state;if(payload?.format!=='nocturne-endurance'||!incoming||!Array.isArray(incoming.exams)||typeof incoming.days!=='object')throw Error('invalid');state={days:incoming.days,dayModes:incoming.dayModes||{},exams:incoming.exams,reviews:{}};delete state.days[DELETED_DAY];ensureDay(today);baseline={};pending=[];saveDraft();save();render();toast('Backup imported; today will sync')}catch{toast('That backup file is not valid')}};reader.readAsText(file)}
function syncLabel(){document.getElementById('sync-banner').hidden=storageOk;document.querySelectorAll('.sync-label').forEach(el=>el.textContent=storageOk?'Saved privately on this device':'Could not save on this device')}
async function flush(){return Promise.resolve()}
function save(){if(!loaded)return Promise.resolve();try{localStorage.setItem(STORE,JSON.stringify(state));storageOk=true}catch{storageOk=false}baseline=flatten(state);syncLabel();return Promise.resolve()}
async function loadState(){main.innerHTML='<div class="empty-state"><strong>Welcome to your practice.</strong>Opening your private journal…</div>';try{const saved=localStorage.getItem(STORE),stored=saved?JSON.parse(saved):null;state=stored?{days:stored.days||{},dayModes:stored.dayModes||{},exams:Array.isArray(stored.exams)?stored.exams:initialState().exams}:initialState()}catch{state=initialState()}delete state.days[DELETED_DAY];baseline=flatten(state);loaded=true;ensureDay(today);save();render()}
function ensureDay(k){if(!state.days[k])state.days[k]={tasks:{},water:0};return state.days[k]}
function isWeekendSchedule(k){const mode=state.dayModes?.[k];return mode==='weekend'||(mode!=='normal'&&(dateFrom(k).getDay()===0||dateFrom(k).getDay()===6))}
function schedule(k){const day=dateFrom(k).getDay(),weekend=isWeekendSchedule(k),friday=day===5&&!weekend;
 const task=(id,name,time,max,penalty,icon,phase,type='simple',detail='')=>({id,name,time,max,penalty,icon,phase,type,detail});
  const tasks=[task('wake','Rise & begin','06:20',70,17.5,'sun','Morning rituals'),task('workout','Move your body','20 MIN',50,12.5,'workout','Morning rituals'),task('journal','A page for yourself','5 MIN',30,7.5,'journal','Morning rituals'),task('meditate','Find your stillness','10 MIN',100,25,'meditate','Morning rituals')];
 if(weekend)tasks.push(task('weekend1','Morning deep work','08:00–11:00',400,100,'focus','The work','focus'),task('weekend2','Midday deep work','11:30–14:00',400,100,'focus','The work','focus'));
 else tasks.push(task('class','Classroom focus','08:00–14:00',100,0,'book','The work','class','Physics · Mathematics · Chemistry'));
 tasks.push(task('afternoon','Afternoon reset','15:20',100,25,'sun','The work'),task('session1','Focus session 01',friday?'15:30–17:30':'15:30–18:00',200,50,'focus','The work','focus'));
 if(friday)tasks.push(task('swimming','Swimming','17:30–19:00',0,0,'swim','The work','simple'));
 tasks.push(task('session2','Focus session 02',friday?'19:00–21:30':'18:30–21:30',200,50,'focus','Evening practice','focus'),task('session3','Focus session 03','22:00–00:00',400,100,'moon','Evening practice','focus'));
 return tasks.map(t=>({...t,icon:t.id}));
}
function entry(k,t){return state.days[k]?.tasks?.[t.id]||null}
function taskXP(t,e,closed=false){if(e?.status==='done')return t.max*((e.rating??100)/100);if(e?.status==='missed'||closed)return -t.penalty;return 0}
function summary(k){const record=state.days[k],tasks=schedule(k),closed=k<today;if(!record)return{xp:0,done:0,total:tasks.length,productivity:null,max:tasks.reduce((n,t)=>n+t.max,100),water:0};
 const water=record.water||0;const scores=tasks.filter(t=>t.max>0).map(t=>{const e=entry(k,t);return e?.status==='done'?(e.rating??100):0});scores.push(water/4*100);
 return{xp:tasks.reduce((n,t)=>n+taskXP(t,entry(k,t),closed),water*25-(closed?(4-water)*5:0)),done:tasks.filter(t=>entry(k,t)?.status==='done').length,total:tasks.length,productivity:Math.round(scores.reduce((a,b)=>a+b,0)/scores.length),max:tasks.reduce((n,t)=>n+t.max,100),water};
}
function xpPercent(k){const st=summary(k);return state.days[k]?st.xp/st.max*100:null}
function qualifies(k){const st=summary(k);return k<=today&&!!state.days[k]&&st.xp+1e-9>=st.max*.8}
function streaks(){const active=Object.keys(state.days).filter(qualifies).sort();let best=0,run=0,prev=null;for(const k of active){run=prev&&offsetDay(prev,1)===k?run+1:1;best=Math.max(best,run);prev=k}let cur=0,k=qualifies(today)?today:offsetDay(today,-1);while(qualifies(k)){cur++;k=offsetDay(k,-1)}return{current:cur,best,active:active.length}}
function toast(s){const t=document.getElementById('toast');t.textContent=s;t.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>t.classList.remove('show'),2500)}
function quoteHtml(){return `<section class="quote dashboard-quote" aria-label="Daily reminder"><div class="quote-top"><span class="eyebrow">Daily reminder</span>${svg('spark')}</div><blockquote>If you want to be the best, you have to do things that other people aren't willing to do.</blockquote></section>`}
function improvementSnippets(){return state.exams.flatMap(exam=>String(exam.improvements||'').split(/\r?\n|[•·]/).map(text=>text.replace(/^\s*[-*\d.)]+\s*/,'').replace(/\s+/g,' ').trim())).filter(Boolean).slice(0,4)}
function glanceItems(items){return `<ol class="glance-timeline">${items.map(item=>`<li><span class="glance-icon" aria-hidden="true">${svg(item[0])}</span><strong>${item[1]}</strong></li>`).join('')}</ol>`}
function glanceSection(number,title,note,items,footer=''){return `<section class="glance-section"><div class="glance-section-head"><span class="glance-number">${number}</span><h3>${title}</h3></div>${glanceItems(items)}</section>`}
function showDailyGlance(){const morning=[['sun','Wake + freshen up'],['workout','Workout'],['drop','Water + dry fruits'],['bath','Bath + wear clothes'],['journal','Journal'],['meditate','Meditation'],['mealMorning','Breakfast']],normal=[...morning,['book','Allen classes'],['mealLunch','Lunch'],['sleepReset','Sleep + reset'],['study1','Study session 01'],['relax1','Relax'],['study2','Study session 02'],['mealDinner','Dinner'],['study3','Study session 03'],['sleep','Sleep']],weekend=[...morning,['study4','Study session 01'],['relax2','Relax'],['study5','Study session 02'],['mealLunch','Lunch'],['sleepReset','Sleep + reset'],['study6','Study session 03'],['relax3','Relax'],['study7','Study session 04'],['mealDinner','Dinner'],['study8','Study session 05'],['sleep','Sleep']],friday='<div class="glance-friday"><span class="glance-icon" aria-hidden="true">'+svg('butterfly')+'</span><strong>Friday swimming</strong></div>';showModal(`${modalHeader('Daily glance','Your day, mapped.')}<div class="glance-map">${glanceSection('01','Normal days','',normal)}${friday}${glanceSection('02','Weekends','',weekend)}</div>`)}
function updateModeButton(){const button=document.getElementById('mode-button');if(!button)return;const weekend=isWeekendSchedule(today);button.classList.toggle('is-weekend',weekend);button.title=weekend?'Use normal schedule':'Use weekend schedule';button.setAttribute('aria-label',weekend?'Switch to normal schedule':'Switch to weekend schedule')}
function toggleScheduleMode(){state.dayModes=state.dayModes||{};const weekend=isWeekendSchedule(today);state.dayModes[today]=weekend?'normal':'weekend';save();render();toast(weekend?'Normal schedule restored':'Weekend schedule enabled for today')}
function statsHtml(st,history=false){const yesterdayKey=offsetDay(today,-1),yesterdayXP=xpPercent(yesterdayKey),todayXP=xpPercent(today),run=streaks(),xpRatio=st.max?st.xp/st.max*100:0,difference=yesterdayXP===null||todayXP===null?null:todayXP-yesterdayXP,comparison=difference===null?(yesterdayXP===null?'No record yet':'Waiting for today'):`${difference>0?'+':difference<0?'-':''}${fmt(Math.abs(difference))}% today vs yesterday`,display=signedXP(st.xp).replace(' XP','');return `<div class="stats"><div class="stat"><div class="stat-title">${svg('spark')}${history?'XP progress':'XP gained'}</div><div class="stat-number">${display}<small>XP</small></div>${history?'':'<div class="stat-percent">'+(todayXP===null?'—':fmt(todayXP)+'% today')+'</div>'}<div class="progress-track"><div class="progress-fill" style="width:${Math.max(0,Math.min(100,xpRatio))}%"></div></div>${history?`<div class="stat-foot">Total XP to date: ${signedXP(st.xp)}</div>`:''}</div><div class="stat"><div class="stat-title">${svg('chart')}${history?'Your best streak':'Yesterday'}</div><div class="stat-number">${history?run.best:(yesterdayXP===null?'—':fmt(yesterdayXP))}<small>${history?'days':yesterdayXP===null?'':'% XP'}</small></div>${history?`<div class="stat-foot">80% XP days</div>`:`<div class="stat-foot stat-comparison">${comparison}</div>`}</div></div>`}
function dayRecordHtml(k){const st=summary(k),waterXP=st.water*25-(k<today?(4-st.water)*5:0);return `<article class="day-record" aria-label="Daily XP record"><div class="record-total"><span>Daily productivity</span><strong>${fmt(xpPercent(k)||0)}% XP</strong></div><div class="record-rows">${schedule(k).map(t=>`<div class="record-row"><span>${t.name}</span><span>${signedXP(taskXP(t,entry(k,t),k<today))}</span></div>`).join('')}<div class="record-row"><span>Hydration</span><span>${signedXP(waterXP)}</span></div></div></article>`}
function taskList(k,editable=canEdit(k)){let phase='';return schedule(k).map(t=>{const e=entry(k,t),done=e?.status==='done',missed=e?.status==='missed'||(!e&&k<today&&!!state.days[k]),earned=taskXP(t,e,k<today&&!!state.days[k]);let heading='';if(phase!==t.phase){phase=t.phase;heading=`<div class="phase-heading">${phase}</div>`}return `${heading}<article class="task-card ${done?'completed':''} ${missed?'missed':''}"><div class="task-symbol"><div class="glyph">${svg(t.icon)}</div><div class="task-time">${t.time}</div></div><div><div class="task-name">${t.name}${t.type==='focus'?'<span class="pill">Focus</span>':''}</div><div class="task-xp">${t.max?`<span class="reward">+${t.max} XP</span><span class="sep">/</span><span>−${fmt(t.penalty)} XP</span>`:'<span>Time to recharge</span>'}</div>${t.detail?`<div class="task-xp">${t.detail}</div>`:''}</div><div class="task-action"><button class="check-button" data-task="${t.id}" data-day="${k}" aria-label="${done?'Review':missed?'Update':'Check in'} ${t.name}" aria-pressed="${done}" ${!editable?'disabled':''}>${svg(missed?'close':'check')}</button>${done||missed?`<span class="earned">${earned>0?'+':''}${fmt(earned)} XP</span>`:''}</div></article>`}).join('')}
function animateElement(el,frames,duration=200){if(!el||matchMedia('(prefers-reduced-motion: reduce)').matches||!el.animate)return;el.getAnimations().forEach(a=>a.cancel());el.animate(frames,{duration,easing:'ease-out'})}
function animateCheck(id){const el=document.querySelector('[data-task="'+id+'"]');el?.classList.remove('is-confirmed');void el?.offsetWidth;el?.classList.add('is-confirmed');animateElement(el?.closest('.task-card'),[{borderColor:'#aaa'},{borderColor:'#303030'}],260)}
function signedXP(n){return (n>0?'+':n<0?'−':'')+fmt(Math.abs(n))+' XP'}
function waterHtml(k){const water=state.days[k]?.water||0;return `<section class="water-panel"><div class="water-head"><span class="eyebrow">Hydration</span>${svg('drop')}</div><div class="water-total">${water}<small> / 4 litres</small></div><div class="water-drops">${[1,2,3,4].map(n=>`<button class="${water>=n?'filled':''}" data-water="${n}" data-day="${k}" aria-label="${n} ${n===1?'litre':'litres'} of water" aria-pressed="${water>=n}" ${!canEdit(k)?'disabled':''}>${svg('drop')}</button>`).join('')}</div><div class="water-meta">+25 XP / litre <span style="margin:0 5px">·</span> −5 XP / litre missed</div></section>`}
function render(){if(!loaded)return;const viewChanged=renderedView!==null&&renderedView!==view;renderedView=view;updateModeButton();document.getElementById('tasks-tab').innerHTML=svg('grid')+'<span>Rituals</span>';document.getElementById('streak-tab').innerHTML=svg('chart')+'<span>Streaks</span>';document.getElementById('tasks-tab').classList.toggle('active',view==='tasks');document.getElementById('streak-tab').classList.toggle('active',view==='streak');document.getElementById('tasks-tab').setAttribute('aria-current',view==='tasks'?'page':'false');document.getElementById('streak-tab').setAttribute('aria-current',view==='streak'?'page':'false');
 if(view==='streak'){renderStreak();const historyTotal=document.querySelector('.history-area .section-head .subtle');if(historyTotal)historyTotal.textContent=state.days[selected]?signedXP(summary(selected).xp):'No recorded activity'}else{const d=dateFrom(today),day=d.toLocaleDateString('en-GB',{weekday:'long'}),date=d.toLocaleDateString('en-GB',{day:'2-digit',month:'2-digit'}).replace('/',' / '),st=summary(today);
  main.innerHTML=`<div class="page-heading"><div><div class="eyebrow">${day} <span class="date-separator">/</span> ${date}</div><h1 class="main-quote">“If you want to be the best, you have to do things that other people aren't willing to do.”</h1></div></div>${statsHtml(st)}${examsHtml()}<section class="task-column"><div class="section-head"><h2>Your rituals</h2><span class="subtle">${fmt(st.xp)} / ${fmt(st.max)} XP</span></div>${taskList(today)}</section>${waterHtml(today)}`}
 bindContent();syncLabel();if(viewChanged)animateElement(main,[{opacity:.55,transform:'translateY(5px)'},{opacity:1,transform:'translateY(0)'}],180);}
function renderStreak(){const monthKey=keyFor(month).slice(0,7),title=month.toLocaleDateString('en-GB',{month:'long',year:'numeric'}),first=(month.getDay()+6)%7,days=new Date(month.getFullYear(),month.getMonth()+1,0).getDate();const run=streaks(),all=Object.keys(state.days).map(summary),totalXP=all.reduce((n,s)=>n+s.xp,0);const stats={xp:totalXP,max:Math.max(1,all.reduce((n,s)=>n+s.max,0))};const records=Object.keys(state.days).filter(k=>k.startsWith(monthKey));const active=records.filter(qualifies).length;const weekStart=offsetDay(selected,-((dateFrom(selected).getDay()+6)%7)),weekEnd=offsetDay(weekStart,6),weekRecords=Object.keys(state.days).filter(k=>k>=weekStart&&k<=weekEnd&&k<=today),weekAvg=weekRecords.length?Math.round(weekRecords.reduce((n,k)=>n+(xpPercent(k)||0),0)/weekRecords.length):null;
 let cells=['Mon','Tue','Wed','Thu','Fri','Sat','Sun'].map(d=>`<div class="weekday">${d}</div>`).join('')+'<span></span>'.repeat(first);
 for(let n=1;n<=days;n++){const k=monthKey+'-'+String(n).padStart(2,'0'),s=summary(k),p=xpPercent(k)||0,level=p>0?Math.max(1,Math.ceil(p/25)):0;cells+=`<button class="day-cell level-${level} ${k===today?'today':''} ${k===selected?'selected':''} ${k>today?'future':''}" data-calendar="${k}" aria-label="${dateFrom(k).toLocaleDateString('en-GB',{day:'numeric',month:'long'})}, ${state.days[k]?`${signedXP(s.xp)} of ${fmt(s.max)} XP`:'no record'}" title="${n} ${title} · ${fmt(p)}% XP" aria-pressed="${k===selected}" ${k>today?'disabled':''}></button>`}
 main.innerHTML=`<div class="page-heading"><div><div class="eyebrow">History</div><h1>Your consistency.</h1></div></div>${statsHtml(stats,true)}<div class="content-grid streak-layout"><section class="task-column"><div class="month-card"><div class="month-heading"><h2>${title}</h2><div class="month-controls"><button class="icon-button" id="prev-month" aria-label="Previous month">${svg('left')}</button><button class="icon-button" id="next-month" aria-label="Next month" ${monthKey>=today.slice(0,7)?'disabled':''}>${svg('right')}</button></div></div><div class="calendar">${cells}</div><div class="legend"><span>${selected<today?'Past entries locked':'Daily XP'}</span><span class="legend-scale">Less ${[0,1,2,3,4].map(n=>`<i class="legend-square level-${n}"></i>`).join('')} More</span></div></div><section class="history-area"><div class="section-head"><h2>${selected===today?'Today':selected===offsetDay(today,-1)?'Yesterday':dateFrom(selected).toLocaleDateString('en-GB',{day:'numeric',month:'long'})}</h2><span class="subtle">${state.days[selected]?`${fmt(summary(selected).xp)} / ${fmt(summary(selected).max)} XP`:'No recorded activity'}</span></div>${state.days[selected]?dayRecordHtml(selected):'<div class="empty-state"><strong>A blank page.</strong>No activity recorded.</div>'}</section></section><aside class="streak-aside"><div class="small-metric"><div class="eyebrow">Days you showed up</div><strong>${active}<span style="color:#727272;font-size:25px"> / ${days}</span></strong><p>80% XP · this month</p></div><div class="small-metric"><div class="eyebrow">Weekly XP</div><strong>${weekAvg??'—'}<span style="color:#727272;font-size:25px">%</span></strong><p>${dateFrom(weekStart).toLocaleDateString('en-GB',{day:'numeric',month:'short'})} – ${dateFrom(weekEnd).toLocaleDateString('en-GB',{day:'numeric',month:'short'})}</p></div></aside></div>`;
}
function bindContent(){document.querySelectorAll('[data-exam]').forEach(b=>b.onclick=()=>editExam(Number(b.dataset.exam)));document.querySelectorAll('[data-task]').forEach(b=>b.onclick=()=>openTask(b.dataset.day,b.dataset.task));document.querySelectorAll('[data-water]').forEach(b=>b.onclick=()=>{if(!canEdit(b.dataset.day))return;const d=ensureDay(b.dataset.day),n=Number(b.dataset.water);d.water=d.water===n?n-1:n;save();render();animateElement(document.querySelector('[data-water="'+n+'"]'),[{transform:'scale(.94)'},{transform:'scale(1)'}]);toast(`${d.water} / 4 litres recorded`)});document.querySelectorAll('[data-calendar]').forEach(b=>b.onclick=()=>{selected=b.dataset.calendar;render()});document.getElementById('prev-month')?.addEventListener('click',()=>{month=new Date(month.getFullYear(),month.getMonth()-1,1);selected=keyFor(month);render()});document.getElementById('next-month')?.addEventListener('click',()=>{month=new Date(month.getFullYear(),month.getMonth()+1,1);selected=keyFor(month).slice(0,7)===today.slice(0,7)?today:keyFor(month);render()})}
function showModal(content){document.getElementById('modal-content').innerHTML=content;modal.showModal();modal.querySelector('[data-close]')?.addEventListener('click',()=>modal.close())}
function modalHeader(eyebrow,title){return `<div class="modal-heading"><div><div class="eyebrow">${eyebrow}</div><h2 id="dialog-title">${title}</h2></div><button class="icon-button" data-close aria-label="Close dialog">${svg('close')}</button></div>`}
function openTask(k,id){if(!canEdit(k)){toast('Past entries are locked.');return}const t=schedule(k).find(x=>x.id===id),e=entry(k,t),done=e?.status==='done';if(t.type==='simple'&&!e&&k===today){ensureDay(k).tasks[id]={status:'done',rating:100};save();render();animateCheck(id);toast(t.max?`+${t.max} XP · A promise kept`:'Swimming complete');return}
 if(t.type==='focus'){const initial=e?.rating??75;showModal(`${modalHeader('A moment of reflection',t.name)}<div class="productivity-value"><span id="rating-number">${initial}</span><small>%</small></div><div class="xp-preview" id="xp-preview">+${fmt(t.max*initial/100)} of ${t.max} XP</div><input type="range" id="rating" aria-label="Session productivity" min="0" max="100" step="1" value="${initial}"><div class="range-labels"><span>A distracted day</span><span>Fully present</span></div><button class="primary-button" id="confirm-task">${done?'Update check-in':'Save my check-in'}</button><button class="secondary-button" id="miss-task">Mark missed · −${t.penalty} XP</button>${e?'<button class="secondary-button" id="undo-task">Clear check-in</button>':''}`);
 const r=document.getElementById('rating');r.oninput=()=>{document.getElementById('rating-number').textContent=r.value;document.getElementById('xp-preview').textContent=`+${fmt(t.max*r.value/100)} of ${t.max} XP`};document.getElementById('confirm-task').onclick=()=>recordTask(k,t,{status:'done',rating:Number(r.value)});
 }else if(t.type==='class'){const values=e?.subjects||[75,75,75];showModal(`${modalHeader('Classroom reflection','Make learning count.')}${['Physics','Mathematics','Chemistry'].map((name,i)=>`<div class="class-row"><div class="class-label"><label for="subject-${i}">${name}</label><span id="subject-value-${i}">${values[i]}%</span></div><input id="subject-${i}" class="subject-range" type="range" min="0" max="100" value="${values[i]}" aria-label="${name} productivity"></div>`).join('')}<div class="xp-preview" id="class-xp"></div><button class="primary-button" id="confirm-task">Save my check-in</button><button class="secondary-button" id="miss-task">Mark missed · 0 XP</button>${e?'<button class="secondary-button" id="undo-task">Clear check-in</button>':''}`);const ranges=[...document.querySelectorAll('.subject-range')];const update=()=>{ranges.forEach((r,i)=>document.getElementById('subject-value-'+i).textContent=r.value+'%');document.getElementById('class-xp').textContent='+'+fmt(ranges.reduce((sum,r,i)=>sum+Number(r.value)*[.33,.33,.34][i],0))+' of 100 XP'};ranges.forEach(r=>r.oninput=update);update();document.getElementById('confirm-task').onclick=()=>{const subjects=ranges.map(r=>Number(r.value));recordTask(k,t,{status:'done',subjects,rating:subjects.reduce((s,v,i)=>s+v*[.33,.33,.34][i],0)})};
 }else{showModal(`${modalHeader('Endurance',t.name)}<button class="primary-button" id="confirm-task">${done?'Keep completed':'Mark complete'}${t.max?' · +'+t.max+' XP':''}</button><button class="secondary-button" id="miss-task">Mark missed · −${fmt(t.penalty)} XP</button>${e?'<button class="secondary-button" id="undo-task">Clear check-in</button>':''}`);document.getElementById('confirm-task').onclick=()=>recordTask(k,t,{status:'done',rating:100})}
 document.getElementById('miss-task').onclick=()=>recordTask(k,t,{status:'missed',rating:0});document.getElementById('undo-task')?.addEventListener('click',()=>{if(!canEdit(k)){modal.close();checkDate();return}delete ensureDay(k).tasks[id];save();modal.close();render();animateCheck(id);toast('Check-in cleared')});}
function recordTask(k,t,data){if(!canEdit(k)){modal.close();checkDate();toast('Past entries are locked.');return}ensureDay(k).tasks[t.id]=data;save();modal.close();render();animateCheck(t.id);const xp=taskXP(t,data);toast(`${xp>0?'+':''}${fmt(xp)} XP · Check-in saved`)}
function showRules(){showModal(`${modalHeader('The details','Your rhythm, explained.')}<ul class="rule-list"><li><strong>Focus XP:</strong> productivity ÷ 100 × the session reward. A 75% session worth 200 XP earns 150 XP.</li><li><strong>Daily productivity:</strong> the average of each XP-bearing ritual’s completion percentage plus hydration. Incomplete rituals count as 0%; class focus uses 33/33/34 subject weights.</li><li><strong>Streaks:</strong> a day counts at 80% of its maximum XP, after penalties and including hydration.</li><li><strong>Missed rituals:</strong> unfinished rituals on recorded past days receive their listed penalty. Today’s pending rituals are not penalised yet. Unrecorded days never create XP debt.</li><li><strong>Your schedule:</strong> the second wake-up is treated as 15:20. Evening sessions finish at midnight. Days close at midnight IST. Past entries are read-only.</li><li><strong>Weekends:</strong> classes become two 400 XP sessions, 08:00–11:00 and 11:30–14:00.</li><li><strong>Fridays:</strong> swimming takes 17:30–19:00. The adjacent focus sessions shorten to fit. Swimming has no XP reward or penalty.</li><li><strong>Water:</strong> your requested target is 4 litres. Tap a droplet to set the total; tap the selected total again to subtract a litre.</li><li><strong>Your data:</strong> saved to your private online journal and available on your devices. If a save cannot connect, your pending changes stay on this browser until you retry.</li></ul><button class="primary-button" data-close-bottom>Back to my practice</button>`);modal.querySelector('[data-close-bottom]').onclick=()=>modal.close()}

Object.assign(ICONS,{
 butterfly:'<path d="M12 10c-1-3-4-6-7-5-2 1-2 5 2 7-4 1-4 5-2 6 3 1 6-2 7-5m0-3c1-3 4-6 7-5 2 1 2 5-2 7 4 1 4 5 2 6-3 1-6-2-7-5M12 8v10"/>',
 code:'<path d="m9 7-4 5 4 5m6-10 4 5-4 5M14 4l-4 16"/>',
 bath:'<path d="M4 13h16M6 13V9a3 3 0 0 1 6 0v1M3 17h18M7 17v3m10-3v3"/>',
 mealMorning:'<path d="M4 14h16M6 14c0-4 2-7 6-7s6 3 6 7M8 18h8M12 7V4"/>',
 mealLunch:'<path d="M4 12h16c0 5-3 8-8 8s-8-3-8-8ZM7 8c1-2 2-3 5-3s4 1 5 3M3 12h18"/>',
 mealDinner:'<circle cx="12" cy="12" r="7"/><path d="M5 12h14M12 5v14M3 4v5m2-5v5m-2 0h2m14-5v7"/>',
 sleepReset:'<path d="M3 16h18M5 16v-5h14v5M7 11V8h4v3m6 5v3M7 16v3"/>',
 sleep:'<path d="M5 18h14M7 18v-7h10v7M9 11V8h6v3M4 6h4M16 6h4"/>',
 study1:'<path d="m5 19 2-5 9-9 3 3-9 9-5 2Zm11-14 2 2M8 16l-1-1"/>',
 study2:'<path d="M4 5h16v14H4zM4 8h16M8 12h8m-8 3h5"/>',
 study3:'<circle cx="12" cy="12" r="8"/><circle cx="12" cy="12" r="3"/><path d="M12 2v2m0 16v2M2 12h2m16 0h2"/>',
 study4:'<path d="M8 3h8l-1 5 4 9a3 3 0 0 1-3 4H8a3 3 0 0 1-3-4l4-9-1-5Zm1 9h6"/>',
 study5:'<rect x="5" y="3" width="14" height="18" rx="2"/><path d="M8 7h8M8 11h2m4 0h2M8 15h2m4 0h2M8 19h2m4 0h2"/>',
 study6:'<path d="M12 3v18M3 12h18M5.5 5.5l13 13m0-13-13 13"/><circle cx="12" cy="12" r="7"/>',
 study7:'<circle cx="12" cy="12" r="8"/><path d="M12 4v8l5 3M12 2v2M12 20v2"/>',
 study8:'<rect x="4" y="5" width="16" height="12" rx="2"/><path d="M8 21h8m-4-4v4"/>',
 relax1:'<path d="M4 17h16M6 17a6 6 0 0 1 12 0M8 12c1-3 3-4 5-3 1-3 4-2 4 1"/>',
 relax2:'<path d="M5 14V9a7 7 0 0 1 14 0v5M5 14h3v-4H5m14 4h-3v-4h3M8 18c2 2 6 2 8 0"/>',
 relax3:'<path d="M12 21V8m0 7c-4 0-6-2-7-6 4 0 6 2 7 6Zm0-4c4 0 6-2 7-6-4 0-6 2-7 6Z"/>',
 wake:'<path d="M3 17h18M5 21h14M7 17a5 5 0 0 1 10 0M12 3v4M4 8l3 3m13-3-3 3"/>',
 workout:'<path d="M3 8v8m4-11v14m0-7h10m0-7v14m4-11v8"/>',
 journal:'<rect x="5" y="3" width="15" height="18" rx="2"/><path d="M8 3v18M3 7h4M3 12h4M3 17h4M12 7h4M12 11h4"/>',
 meditate:'<path d="M12 21v-9M12 16C5 16 3 12 3 7c6 0 9 3 9 9Zm0-4c0-6 3-9 9-9 0 6-3 9-9 9ZM8 21h8"/>',
 weekend1:'<circle cx="12" cy="12" r="3"/><path d="M8 3H3v5m13-5h5v5M3 16v5h5m8 0h5v-5"/>',
 weekend2:'<rect x="4" y="4" width="16" height="16" rx="4"/><path d="M8 16V9m4 7V7m4 9v-4"/>',
 class:'<path d="m2 9 10-5 10 5-10 5L2 9Zm4 2v6c4 3 8 3 12 0v-6m4-2v8"/>',
 afternoon:'<circle cx="12" cy="13" r="7"/><path d="M12 9v5h4M4 3 1 6m19-3 3 3M7 20l-1 2m11-2 1 2"/>',
 session1:'<circle cx="12" cy="12" r="8"/><circle cx="12" cy="12" r="3"/><path d="M12 2v2m0 16v2M2 12h2m16 0h2"/>',
 session2:'<path d="M6 3h12M6 21h12M7 3v4l10 10v4M17 3v4 0L7 17v4M7 7l10 10M9 18h6"/>',
 session3:'<path d="M4 5h16v12H4zM8 21h8m-4-4v4M7 9h2m2 0h6M7 13h10"/>',
 swimming:'<path d="M3 18q3-3 6 0t6 0 6 0M3 22q3-3 6 0t6 0 6 0M5 13l6-6 5 6M8 5l4-2 5 3"/><circle cx="19" cy="10" r="2"/>',
 review:'<rect x="5" y="4" width="14" height="17" rx="2"/><path d="M9 2h6v4H9zM9 11h6m-6 4h3"/>',
 exam:'<rect x="3" y="5" width="18" height="16" rx="3"/><path d="M7 3v4m10-4v4M3 11h18m-13 5h3"/>',
  plus:'<path d="M12 5v14M5 12h14"/>',
  glance:'<rect x="4" y="4" width="16" height="16" rx="3"/><path d="M8 2v4m8-4v4M4 10h16M8 14h3m-3 3h6"/>',
  mode:'<path d="M5 7h11m-3-3 3 3-3 3M19 17H8m3-3-3 3 3 3"/>'
});
function examsHtml(){const labels=['Exam','Pattern'],date=state.exams[0].date||state.exams[1].date,days=date?Math.round((Date.parse(date)-Date.parse(today))/86400000):null,names=state.exams.map((exam,i)=>`<span class="exam-name-line"><strong>${esc(exam.name||labels[i])}</strong></span>`).join(''),snippets=improvementSnippets(),notes=snippets.length?snippets.map(snippet=>`<span class="exam-improvement">${esc(snippet)}</span>`).join(''):'<span class="exam-empty">Add a focus note</span>',countdown=days===null?'—':days===0?'Today':Math.abs(days),countdownLabel=days===0?'':`<span>${days!==null&&days<0?'days ago':'days to go'}</span>`;return `<section class="exam-section"><div class="exam-card-pair"><button class="exam-card next-exam-card" data-exam="0" aria-label="Edit exam, pattern, and shared date"><span class="exam-top">${svg('exam')}<span>NEXT EXAM</span><span class="exam-date">${date?dateFrom(date).toLocaleDateString('en-GB',{day:'numeric',month:'short'}):'Set date'}</span>${svg('edit')}</span><span class="exam-body"><span class="exam-names">${names}</span><span class="exam-countdown"><b>${countdown}</b>${countdownLabel}</span></span></button><div class="exam-card notes-card" aria-label="Exam notes"><span class="exam-top">${svg('journal')}<span>EXAM NOTES</span></span><span class="exam-improvement-list">${notes}</span></div></div></section>`}
function editExam(){const labels=['Exam','Pattern'];showModal(`${modalHeader('Exam and pattern','Next exam day')}<form id="exam-form">${state.exams.map((exam,i)=>`<label class="form-label" for="exam-name-${i}">${labels[i]}</label><input id="exam-name-${i}" type="text" maxlength="60" value="${esc(exam.name)}" placeholder="${labels[i]}">`).join('')}<label class="form-label" for="exam-date">Shared date</label><input id="exam-date" type="date" value="${esc(state.exams[0].date||state.exams[1].date)}">${state.exams.map((exam,i)=>`<details class="exam-notes" ${exam.improvements?'open':''}><summary>${labels[i]} · improvements</summary><textarea id="exam-improvements-${i}" aria-label="${labels[i]} improvements" maxlength="3000">${esc(exam.improvements)}</textarea></details>`).join('')}<button class="primary-button" type="submit">Save</button></form>`);document.getElementById('exam-form').onsubmit=e=>{e.preventDefault();const date=document.getElementById('exam-date').value;const names=[0,1].map(i=>document.getElementById('exam-name-'+i).value.trim());const input=document.getElementById('exam-date');input.setCustomValidity(names.some(Boolean)&&!date?'Choose the shared exam date.':'');if(!document.getElementById('exam-form').reportValidity())return;state.exams=names.map((name,i)=>({name,date,improvements:document.getElementById('exam-improvements-'+i).value.trim()}));save();modal.close();render();toast('Exam details saved')};document.getElementById('exam-date').oninput=e=>e.target.setCustomValidity('')}

const glanceButton=document.createElement('button');glanceButton.className='icon-button';glanceButton.id='glance-button';glanceButton.innerHTML=svg('glance');glanceButton.setAttribute('aria-label','Open daily glance');glanceButton.title='Daily glance';const modeButton=document.createElement('button');modeButton.className='icon-button';modeButton.id='mode-button';modeButton.innerHTML=svg('mode');document.querySelector('.header-actions').insertBefore(glanceButton,document.getElementById('rules-button'));document.querySelector('.header-actions').insertBefore(modeButton,document.getElementById('rules-button'));glanceButton.onclick=showDailyGlance;modeButton.onclick=toggleScheduleMode;document.getElementById('rules-button').innerHTML=svg('info');document.getElementById('rules-button').onclick=showRules;document.getElementById('export-button').onclick=exportData;document.getElementById('import-button').onclick=()=>document.getElementById('import-file').click();document.getElementById('import-file').onchange=e=>{importData(e.target.files?.[0]);e.target.value=''};
document.getElementById('tasks-tab').onclick=()=>{view='tasks';render();window.scrollTo({top:0,behavior:'smooth'})};document.getElementById('streak-tab').onclick=()=>{view='streak';selected=offsetDay(today,-1);month=new Date(dateFrom(selected).getFullYear(),dateFrom(selected).getMonth(),1);render();window.scrollTo({top:0,behavior:'smooth'})};document.querySelector('.brand').onclick=e=>{e.preventDefault();view='tasks';render();window.scrollTo({top:0,behavior:'smooth'})};modal.addEventListener('click',e=>{if(e.target===modal){const r=modal.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)modal.close()}});
function checkDate(){const now=currentDay();if(now!==today){if(modal.open)modal.close();today=now;selected=today;ensureDay(today);save();render();}}
document.addEventListener('visibilitychange',()=>{if(!document.hidden&&loaded){checkDate();}});setInterval(()=>{if(loaded){checkDate();}},1000);window.addEventListener('online',()=>flush());window.addEventListener('beforeunload',e=>{if(pending.length){e.preventDefault();e.returnValue=''}});loadState();

const context=document.modelContext;
if(context?.registerTool){
 const controller=new AbortController();
 const tools=[{
  name:'get_daily_progress',title:'Read daily progress',description:'Read the current day’s schedule, XP, check-ins and hydration without changing any records.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:false},execute(input){if(!loaded)throw new Error('Journal is still loading');if(Object.keys(input||{}).length)throw new Error('No arguments accepted');return {date:today,...summary(today),rituals:schedule(today).map(t=>({id:t.id,name:t.name,time:t.time,maxXP:t.max,checkin:entry(today,t)}))}}},
 {name:'set_water_intake',title:'Record today’s water intake',description:'Set today’s total water intake between 0 and 4 litres, save it and update the visible tracker.',inputSchema:{type:'object',properties:{litres:{type:'integer',minimum:0,maximum:4}},required:['litres'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},async execute(input){if(!loaded)throw new Error('Journal is still loading');if(!input||Object.keys(input).length!==1||!Number.isInteger(input.litres)||input.litres<0||input.litres>4)throw new Error('Litres must be an integer from 0 to 4');checkDate();ensureDay(today).water=input.litres;await save();render();if(!storageOk)throw new Error('Change recorded but waiting to sync');return {date:today,litres:input.litres,xp:summary(today).xp,saved:true}}}
 ];for(const tool of tools){try{Promise.resolve(context.registerTool(tool,{signal:controller.signal})).catch(()=>{})}catch{}}window.addEventListener('pagehide',()=>controller.abort(),{once:true});
}
